USE [Dealer]
GO
--insertar en la tabla de proveedores
INSERT INTO [dbo].proveedor ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Honda Dominicana','00155415','HondaDominicana@gmail.com','Av. John F. Kennedy, Santo Domingo')
	 
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[proveedor] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')

INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('Ramon','Tolentino','0013458464','Naco city')

	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')
	 INSERT INTO [dbo].[Cliente] ([Nombre],[Cedula],[Correo],[Direccion])
     VALUES ('','','','')




INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('Honda','Accord','6c','4','Sedan','K54854s284f6',1,2015)

	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)
	 INSERT INTO [dbo].[AutoMovil] ([Marca],[Modelo],[CC],[Puerta],[Tipo],[Chasis],[id_proveedor],ano)
     VALUES ('','','','','','',0,0)

           
INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES ('Retrovisor derecho',2,'Honda Civic 2010',1)           
	 
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           
	 INSERT INTO [dbo].[inventario] ([Descripcion],[Cant],[carro],[id_proveedor])
     VALUES (' ',0,'',0)           

  
INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (1,1,950000.50,'T')

	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')
	 INSERT INTO [dbo].[Venta] ([id_cliente],[id_AutoMovil],[Precio],[Tip_pago])
     VALUES (0,0,0.0,'')

GO


